/* tslint:disable */
/* eslint-disable */
/**
 * Cronuseo
 * This is the cronuseo backend APIs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GroupCreationRequestBodyGroupProperties } from './group-creation-request-body-group-properties';

/**
 * 
 * @export
 * @interface GroupUpdateRequestBody
 */
export interface GroupUpdateRequestBody {
    /**
     * 
     * @type {GroupCreationRequestBodyGroupProperties}
     * @memberof GroupUpdateRequestBody
     */
    'group_properties'?: GroupCreationRequestBodyGroupProperties;
}

