/* tslint:disable */
/* eslint-disable */
/**
 * Cronuseo
 * This is the cronuseo backend APIs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GroupPatchRequestBody
 */
export interface GroupPatchRequestBody {
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupPatchRequestBody
     */
    'added_roles'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupPatchRequestBody
     */
    'added_users'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupPatchRequestBody
     */
    'added_policies'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupPatchRequestBody
     */
    'removed_roles'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupPatchRequestBody
     */
    'removed_users'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupPatchRequestBody
     */
    'removed_policies'?: Array<string>;
}

