/* tslint:disable */
/* eslint-disable */
/**
 * Cronuseo
 * This is the cronuseo backend APIs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AssignedRole } from './assigned-role';
// May contain unused imports in some cases
// @ts-ignore
import { Policy } from './policy';
// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * 
 * @export
 * @interface GroupEntity
 */
export interface GroupEntity {
    /**
     * 
     * @type {string}
     * @memberof GroupEntity
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupEntity
     */
    'display_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupEntity
     */
    'identifier'?: string;
    /**
     * 
     * @type {Array<AssignedRole>}
     * @memberof GroupEntity
     */
    'roles'?: Array<AssignedRole>;
    /**
     * 
     * @type {Array<User>}
     * @memberof GroupEntity
     */
    'users'?: Array<User>;
    /**
     * 
     * @type {Array<Policy>}
     * @memberof GroupEntity
     */
    'policies'?: Array<Policy>;
}

