/* tslint:disable */
/* eslint-disable */
/**
 * Cronuseo
 * This is the cronuseo backend APIs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GroupCreationRequestBodyGroupProperties
 */
export interface GroupCreationRequestBodyGroupProperties {
    /**
     * 
     * @type {number}
     * @memberof GroupCreationRequestBodyGroupProperties
     */
    'max_limit'?: number;
}

