/* tslint:disable */
/* eslint-disable */
/**
 * Cronuseo
 * This is the cronuseo backend APIs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PolicyEntity
 */
export interface PolicyEntity {
    /**
     * 
     * @type {string}
     * @memberof PolicyEntity
     */
    'identifier': string;
    /**
     * 
     * @type {string}
     * @memberof PolicyEntity
     */
    'active_version'?: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyEntity
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyEntity
     */
    'policy'?: string;
}

