/* tslint:disable */
/* eslint-disable */
/**
 * Cronuseo
 * This is the cronuseo backend APIs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ActionEntity } from './action-entity';

/**
 * 
 * @export
 * @interface ResourceEntity
 */
export interface ResourceEntity {
    /**
     * 
     * @type {string}
     * @memberof ResourceEntity
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceEntity
     */
    'display_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceEntity
     */
    'identifier'?: string;
    /**
     * 
     * @type {Array<ActionEntity>}
     * @memberof ResourceEntity
     */
    'actions'?: Array<ActionEntity>;
}

