/* tslint:disable */
/* eslint-disable */
/**
 * Cronuseo
 * This is the cronuseo backend APIs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Action } from './action';

/**
 * 
 * @export
 * @interface ResourcePatchRequestBody
 */
export interface ResourcePatchRequestBody {
    /**
     * 
     * @type {Array<Action>}
     * @memberof ResourcePatchRequestBody
     */
    'added_actions'?: Array<Action>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ResourcePatchRequestBody
     */
    'removed_actions'?: Array<string>;
}

