/* tslint:disable */
/* eslint-disable */
/**
 * Cronuseo
 * This is the cronuseo backend APIs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoleCreationRequestBody
 */
export interface RoleCreationRequestBody {
    /**
     * 
     * @type {string}
     * @memberof RoleCreationRequestBody
     */
    'display_name': string;
    /**
     * 
     * @type {string}
     * @memberof RoleCreationRequestBody
     */
    'identifier': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RoleCreationRequestBody
     */
    'groups'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RoleCreationRequestBody
     */
    'users'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RoleCreationRequestBody
     */
    'permissions'?: Array<string>;
}

