/* tslint:disable */
/* eslint-disable */
/**
 * Cronuseo
 * This is the cronuseo backend APIs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserCreationRequestBodyUserProperties } from './user-creation-request-body-user-properties';

/**
 * 
 * @export
 * @interface UserUpdateRequestBody
 */
export interface UserUpdateRequestBody {
    /**
     * 
     * @type {UserCreationRequestBodyUserProperties}
     * @memberof UserUpdateRequestBody
     */
    'user_properties'?: UserCreationRequestBodyUserProperties;
}

