/* tslint:disable */
/* eslint-disable */
/**
 * Cronuseo
 * This is the cronuseo backend APIs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserCreationRequestBodyUserProperties } from './user-creation-request-body-user-properties';

/**
 * 
 * @export
 * @interface UserCreationRequestBody
 */
export interface UserCreationRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UserCreationRequestBody
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserCreationRequestBody
     */
    'identifier': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserCreationRequestBody
     */
    'groups'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserCreationRequestBody
     */
    'roles'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserCreationRequestBody
     */
    'policies'?: Array<string>;
    /**
     * 
     * @type {UserCreationRequestBodyUserProperties}
     * @memberof UserCreationRequestBody
     */
    'user_properties'?: UserCreationRequestBodyUserProperties;
}

