/* tslint:disable */
/* eslint-disable */
/**
 * Cronuseo
 * This is the cronuseo backend APIs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AssignedGroup } from './assigned-group';
// May contain unused imports in some cases
// @ts-ignore
import { AssignedRole } from './assigned-role';
// May contain unused imports in some cases
// @ts-ignore
import { Policy } from './policy';
// May contain unused imports in some cases
// @ts-ignore
import { UserCreationRequestBodyUserProperties } from './user-creation-request-body-user-properties';

/**
 * 
 * @export
 * @interface UserEntity
 */
export interface UserEntity {
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'identifier'?: string;
    /**
     * 
     * @type {Array<AssignedGroup>}
     * @memberof UserEntity
     */
    'groups'?: Array<AssignedGroup>;
    /**
     * 
     * @type {Array<AssignedRole>}
     * @memberof UserEntity
     */
    'roles'?: Array<AssignedRole>;
    /**
     * 
     * @type {Array<Policy>}
     * @memberof UserEntity
     */
    'policies'?: Array<Policy>;
    /**
     * 
     * @type {UserCreationRequestBodyUserProperties}
     * @memberof UserEntity
     */
    'user_properties'?: UserCreationRequestBodyUserProperties;
}

